// Master B2B Content Database for Everest Air Conditioning Company

export const industries = [
  {
    id: "hospitals",
    name: "Hospitals & Healthcare",
    challenges: [
      "Critical pressure hierarchy control between operating theaters, isolation wards, and common spaces.",
      "Strict indoor air quality (IAQ) and high-efficiency particulate air (HEPA) filtration requirements.",
      "24/7/365 continuous operational uptime with high redundancy expectations.",
      "Strict humidity control to prevent bacterial growth and optimize patient comfort."
    ],
    solutions: "Custom hygienic Air Handling Units (AHUs), medical-grade filtration systems, Laminar flow ceilings, and highly redundant central Chiller plants with automated BMS integration.",
    benefits: "Zero airborne infection risk, 99.97% pathogen filtration efficiency, regulatory compliance (NABH standard), and robust emergency failover systems.",
    projectsCount: 42,
    shortDesc: "Critical hygiene & pressure control HVAC solutions."
  },
  {
    id: "hotels",
    name: "Hotels & Hospitality",
    challenges: [
      "Drastic seasonal and daily load fluctuations demanding efficient part-load operation.",
      "Strict acoustic requirements (low sound level) to ensure guest comfort.",
      "Complex multi-zone controls for guestrooms, banquet halls, kitchens, and lobbies."
    ],
    solutions: "Vibration-isolated VRF systems for individual guest rooms and low-noise air-cooled screw chillers with thermal storage for larger banquet halls and lobbies.",
    benefits: "Significant energy cost reductions, decentralized guest control, and silent operation below 30dBA in guest suites.",
    projectsCount: 38,
    shortDesc: "Low noise, high comfort zonal cooling systems."
  },
  {
    id: "commercial-offices",
    name: "Commercial Offices",
    challenges: [
      "High density occupancy and heat load from office equipment.",
      "Varying heating/cooling demands for perimeter vs interior zones.",
      "Fresh air ventilation compliance to combat Sick Building Syndrome."
    ],
    solutions: "Energy-efficient VRF systems with heat recovery, centralized fresh air AHUs with Heat Recovery Wheels, and smart thermostats.",
    benefits: "Individual zone control, 30% reduction in heating/cooling energy, and productivity gains via improved CO2 levels.",
    projectsCount: 85,
    shortDesc: "Multi-zone comfort & fresh-air ventilation."
  },
  {
    id: "factories",
    name: "Factories & Industrial Plants",
    challenges: [
      "Massive heat loads generated by industrial machinery.",
      "Heavy dust, oil mist, and chemical pollutants in the air.",
      "Requirement for precise cooling of specific equipment or process zones."
    ],
    solutions: "Heavy-duty industrial air washers, evaporative cooling systems, ducting networks, and specialized process cooling chiller loops.",
    benefits: "Improved worker safety & productivity, dust-free manufacturing floors, and prolonged machinery lifespan.",
    projectsCount: 64,
    shortDesc: "Heavy duty process cooling & ventilation."
  },
  {
    id: "it-parks",
    name: "IT Parks & Data Centers",
    challenges: [
      "Extremely high sensible heat ratios and constant thermal loads.",
      "High energy consumption and massive operational carbon footprint.",
      "Requirement for precise hot/cold aisle containment."
    ],
    solutions: "Precision Air Conditioning (PAC) units, water-cooled centrifugal chiller plants with variable primary flow, and under-floor air distribution systems.",
    benefits: "Guaranteed PUE (Power Usage Effectiveness) below 1.4, 99.999% uptime, and dynamic sensible heat extraction.",
    projectsCount: 48,
    shortDesc: "Precision cooling for heavy computing loads."
  },
  {
    id: "cold-storage",
    name: "Cold Storage & Logistics",
    challenges: [
      "Maintaining strict sub-zero temperature ranges consistently.",
      "High thermal shock risks during loading and unloading.",
      "Moisture control to prevent frost build-up on products."
    ],
    solutions: "Heavy-duty ammonia or Freon-based industrial refrigeration units, insulated panel ducting, air curtains, and remote IoT temperature telemetry.",
    benefits: "Zero spoilage guarantee, accurate temperature hold down to -25°C, and automated defrost cycles.",
    projectsCount: 29,
    shortDesc: "Reliable sub-zero thermal preservation."
  },
  {
    id: "pharmaceutical",
    name: "Pharmaceutical Plants",
    challenges: [
      "Strict compliance with USFDA, WHO-GMP, and schedule M guidelines.",
      "Absolute control of relative humidity (RH) down to 35% for powder processing.",
      "Stringent cross-contamination prevention guidelines."
    ],
    solutions: "Dehumidification rotors, safe-change HEPA filter housings, closed-loop return systems, and comprehensive validation documentation (DQ/IQ/OQ/PQ).",
    benefits: "FDA audit approval assurance, total particle containment, and stable environment for drug formulation.",
    projectsCount: 35,
    shortDesc: "USFDA/GMP compliant HVAC environments."
  },
  {
    id: "shopping-malls",
    name: "Shopping Malls & Retail",
    challenges: [
      "Unpredictable crowd density changes throughout the day.",
      "Large open spaces with high ceiling heights and thermal envelope losses.",
      "Aesthetic integration of visible ductwork."
    ],
    solutions: "High tonnage centrifugal chillers, variable air volume (VAV) systems, and large-capacity double-skin air handling units.",
    benefits: "Optimized part-load energy costs, uniform cooling without hot spots, and stylish exposed-duct aesthetics.",
    projectsCount: 31,
    shortDesc: "Large-scale variable load comfort cooling."
  },
  {
    id: "educational-institutions",
    name: "Educational Institutions",
    challenges: [
      "Budget constraints coupled with high occupancy levels.",
      "Intermittent schedules (operational vs vacation periods).",
      "Low carbon footprint target and high sustainability focus."
    ],
    solutions: "Eco-friendly VRF installations, smart control schedulers, and centralized DX systems for auditoriums and labs.",
    benefits: "Zero power wastage during holidays, quiet classroom environments, and highly scalable installations.",
    projectsCount: 40,
    shortDesc: "High occupancy, cost-effective ventilation."
  }
];

export const solutions = [
  {
    id: "commercial-hvac",
    name: "Commercial HVAC Design & Build",
    desc: "Complete end-to-end HVAC contracting from heat load calculations and design layouts to supply, execution, testing, and commissioning.",
    highlights: ["Heat Load Calculations (ASHRAE standards)", "3D CAD & BIM Coordination modeling", "High efficiency duct routing design", "Rigorous testing and commissioning protocol"]
  },
  {
    id: "vrf-installation",
    name: "VRF / VRV System Installation",
    desc: "Variable Refrigerant Flow systems perfect for multi-zone requirements like hotels, luxury residences, and commercial offices.",
    highlights: ["Simultaneous heating and cooling", "Inverter compressor technology for part loads", "Minimal ducting space required", "Brands: Daikin, Mitsubishi, LG, Blue Star"]
  },
  {
    id: "chiller-plants",
    name: "Chiller Plants & Piping",
    desc: "Large capacity central cooling solutions employing water-cooled or air-cooled screw and centrifugal chillers.",
    highlights: ["High tonnage capacity (100 TR to 2000+ TR)", "Heavy-duty MS/GI chiller piping", "Cooling towers & primary/secondary pump integration", "Smart PLC & BMS manager boards"]
  },
  {
    id: "ahu-systems",
    name: "Air Handling Unit (AHU) Systems",
    desc: "Custom double-skin AHUs with filtration, cooling coils, heat recovery, and fans to circulate and condition air.",
    highlights: ["Double skin panels (50mm/25mm)", "Hygienic class structures for hospitals", "Thermal break profiles to prevent condensation", "EC plug fans for high energy savings"]
  },
  {
    id: "ventilation-systems",
    name: "Industrial Ventilation & Exhaust",
    desc: "Basement ventilation, commercial kitchen exhaust, toilet exhaust, and factory fresh-air systems to maintain positive/negative pressures.",
    highlights: ["Jet fan basement ventilation", "Treated Fresh Air (TFA) units", "Scrubber systems for commercial kitchens", "Smoke extraction systems compliance"]
  },
  {
    id: "cold-storage-solution",
    name: "Cold Storage Construction",
    desc: "Walk-in cold rooms, deep freezers, and industrial refrigeration for agriculture, dairy, and pharmaceuticals.",
    highlights: ["Temperature range: +15°C to -40°C", "PUF insulation panel setup", "Anti-bacterial floor and wall surfaces", "Remote IoT temperature logs & alarms"]
  },
  {
    id: "hvac-retrofit",
    name: "HVAC Retrofit & Refurbishment",
    desc: "Upgrade legacy, low-efficiency systems to modern high-efficiency chillers or VRFs without major business downtime.",
    highlights: ["Energy auditing of old systems", "Phased demolition and retrofitting", "Equipment replacement (compressors, coils)", "Payback analysis in under 3 years"]
  },
  {
    id: "energy-saving",
    name: "Energy Saving Solutions",
    desc: "Optimization of existing HVAC networks using Variable Frequency Drives (VFDs), smart sensors, and advanced control strategies.",
    highlights: ["VFDs on pumps & AHU fans", "BMS automation programming", "Sensible and Latent heat recovery wheels", "ROI and carbon footprint tracking reports"]
  }
];

export const ongoingProjects = [
  {
    id: "on-1",
    image: "/logos/destylus.png",
    name: "Destylus Designers Pvt Ltd",
    customer: "Destylus Designers Pvt Ltd",
    location: "T-Nagar, Chennai",
    capacity: "11.5 TR/HP",
    scope: "Turnkey Commercial VRF Inverter Installation & Aesthetic Exposed Ducting",
    progress: "85%",
    currentPhase: "System Commissioning & Air Balancing",
    expectedCompletion: "Q2 2026",
    year: "Ongoing",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "ongoing",
    description: "Design studio and corporate office multi-zone VRF HVAC installation with high-efficiency air distribution."
  },
  {
    id: "on-2",
    image: "/logos/house-of-cloths.svg",
    name: "House of Cloths",
    customer: "House of Cloths",
    location: "Perambur, Chennai",
    capacity: "6 TR/HP",
    scope: "Commercial Cassette & Split HVAC Network with Treated Fresh Air",
    progress: "70%",
    currentPhase: "Copper Piping & Indoor Units Setup",
    expectedCompletion: "Q2 2026",
    year: "Ongoing",
    industry: "shopping-malls",
    brand: "Blue Star",
    status: "ongoing",
    description: "Retail showroom comfort cooling setup with discrete cassette ceiling integration and uniform airflow."
  },
  {
    id: "on-3",
    image: "/logos/tmb-bank.svg",
    name: "TMB Bank (Nerkundram Branch)",
    customer: "TMB Bank",
    location: "Nerkundram, Chennai",
    capacity: "4.2 TR/HP",
    scope: "Banking Branch Inverter AC & Fresh Air Ventilation System",
    progress: "90%",
    currentPhase: "Final Electrical Integration & Testing",
    expectedCompletion: "Q2 2026",
    year: "Ongoing",
    industry: "commercial-offices",
    brand: "Carrier",
    status: "ongoing",
    description: "Commercial branch air conditioning with continuous air exchange and energy-saving inverter technology."
  },
  {
    id: "on-4",
    image: "/logos/anna-gowri.png",
    name: "Anna Gowri Educational Trust (Campus Extension)",
    customer: "Anna Gowri Educational Trust",
    location: "Puttur, Andhra Pradesh",
    capacity: "High Tonnage Central Plant",
    scope: "Central Air Conditioning & Campus Ventilation Infrastructure",
    progress: "50%",
    currentPhase: "Main Plant Ducting & Riser Installation",
    expectedCompletion: "Q3 2026",
    year: "Ongoing",
    industry: "educational-institutions",
    brand: "Voltas",
    status: "ongoing",
    description: "Multi-block institutional cooling system covering academic lecture halls, library, and faculty zones."
  },
  {
    id: "on-5",
    image: "/logos/abs-general.svg",
    name: "ABS General HVAC Solutions (MSME Facility)",
    customer: "ABS General HVAC Solutions",
    location: "MSME, Oragadam, Chennai",
    capacity: "Turnkey Industrial Plant",
    scope: "Heavy-Duty Industrial Process Ventilation & Equipment Cooling",
    progress: "60%",
    currentPhase: "Industrial Ducting Network & Air Washer Assembly",
    expectedCompletion: "Q4 2026",
    year: "Ongoing",
    industry: "factories",
    brand: "Blue Star",
    status: "ongoing",
    description: "Turnkey industrial ventilation and precision air handling for auto-component and MSME manufacturing operations."
  }
];

export const completedProjects = [
  {
    id: "comp-2",
    image: "/logos/anna-gowri.png",
    name: "Anna Gowri Educational Trust",
    customer: "Anna Gowri Educational Trust",
    location: "Puttur, Andhra Pradesh",
    capacity: "340 TR/HP",
    scope: "Campus-Wide Central Air Conditioning, Chiller Piping & Auditorium HVAC",
    year: "2023",
    industry: "educational-institutions",
    brand: "Voltas",
    status: "completed",
    description: "Large-scale institutional cooling network with low-noise air distribution across auditoriums and academic blocks."
  },
  {
    id: "comp-1",
    image: "/logos/cryolor.svg",
    name: "Cryolor Asia Pacific",
    customer: "Cryolor Asia Pacific",
    location: "Madurantakam, Tamil Nadu",
    capacity: "74 TR/HP",
    scope: "Industrial Cryogenic Manufacturing Facility HVAC & Process Cooling Loop",
    year: "2024",
    industry: "factories",
    brand: "Carrier",
    status: "completed",
    description: "Turnkey air management and specialized process cooling for precision cryogenic equipment manufacturing."
  },
  {
    id: "comp-19",
    image: "/logos/global-software.svg",
    name: "Global Software Tech Hub",
    customer: "Global Software",
    location: "Siruseri IT Corridor, Chennai",
    capacity: "51 TR/HP",
    scope: "IT Development Floor VRF System + Server Room PAC Unit",
    year: "2024",
    industry: "it-parks",
    brand: "Johnson Controls",
    status: "completed",
    description: "24/7 mission-critical software engineering facility cooling with high sensible heat removal and IoT monitoring."
  },
  {
    id: "comp-4",
    image: "/logos/agile-robots.svg",
    name: "Agile Robots (Plant 1)",
    customer: "Agile Robots",
    location: "Irrungattukottai Industrial Hub",
    capacity: "45 TR/HP",
    scope: "High-Tech Robotics Assembly Floor Clean Ventilation & VRF Network",
    year: "2024",
    industry: "factories",
    brand: "Blue Star",
    status: "completed",
    description: "Dust-free precision climate system maintaining positive pressure for robotic arms manufacturing."
  },
  {
    id: "comp-13",
    image: "/logos/pn-rao.png",
    name: "P.N. Rao Flagship Store",
    customer: "P.N. Rao",
    location: "Alwarpet, Chennai",
    capacity: "42 TR/HP",
    scope: "Premium Retail Store VRF System with Exposed Architectural Spiral Ducting",
    year: "2024",
    industry: "shopping-malls",
    brand: "Daikin",
    status: "completed",
    description: "Designer retail HVAC featuring aesthetic black spiral ductwork, precise humidity control, and part-load efficiency."
  },
  {
    id: "comp-3",
    image: "/logos/fortunetech.svg",
    name: "Fortunetech Technologies",
    customer: "Fortunetech Technologies",
    location: "Mannur, Tamil Nadu",
    capacity: "36 TR/HP",
    scope: "Precision Engineering & Tech Facility Climate System + Clean Air AHUs",
    year: "2023",
    industry: "it-parks",
    brand: "Daikin",
    status: "completed",
    description: "Precision thermal management and server room environmental controls for high-tech manufacturing."
  },
  {
    id: "comp-9",
    image: "/logos/eternal-enterprises.svg",
    name: "Eternal Enterprises",
    customer: "Eternal Enterprises",
    location: "Chromepet, Chennai",
    capacity: "36 TR/HP",
    scope: "Commercial Showroom & Corporate Complex Ductable Split System",
    year: "2023",
    industry: "commercial-offices",
    brand: "Voltas",
    status: "completed",
    description: "High-airflow ductable cooling designed for high-density customer footfall and product display zones."
  },
  {
    id: "comp-7",
    image: "/logos/soliss.svg",
    name: "Soliss Restaurant",
    customer: "Soliss Restaurant",
    location: "Injambakkam, ECR Chennai",
    capacity: "26 TR/HP",
    scope: "Dining Hall Comfort HVAC + Heavy-Duty Kitchen Exhaust & Scrubber",
    year: "2024",
    industry: "hotels",
    brand: "Blue Star",
    status: "completed",
    description: "High-comfort dining cooling combined with high-velocity kitchen hood ventilation and odor elimination."
  },
  {
    id: "comp-5",
    image: "/logos/agile-robots.svg",
    name: "Agile Robots (Plant 2)",
    customer: "Agile Robots",
    location: "Irrungattukottai Industrial Hub",
    capacity: "25 TR/HP",
    scope: "Robotics R&D Lab & Engineering Office Inverter Air Conditioning",
    year: "2024",
    industry: "factories",
    brand: "Daikin",
    status: "completed",
    description: "Multi-zone VRF system with whisper-quiet indoor units for robotics testing labs and design offices."
  },
  {
    id: "comp-16",
    image: "/logos/aiadmk.svg",
    name: "AIADMK Office",
    customer: "AIADMK Office",
    location: "Royapettah, Chennai",
    capacity: "20 TR/HP",
    scope: "Administrative Complex Centralized Cooling & Meeting Hall HVAC",
    year: "2023",
    industry: "commercial-offices",
    brand: "Blue Star",
    status: "completed",
    description: "High-capacity air conditioning system engineered for heavy intermittent crowd loads in conference halls."
  },
  {
    id: "comp-12",
    image: "/logos/arivupro.webp",
    name: "Arivu Educational Consultants",
    customer: "Arivu Educational Consultants",
    location: "Tambaram, Chennai",
    capacity: "19.1 TR/HP",
    scope: "Educational Consultancy Center Ductable AC & Fresh Air System",
    year: "2023",
    industry: "educational-institutions",
    brand: "Blue Star",
    status: "completed",
    description: "Continuous fresh-air circulation and balanced cooling across seminar halls and student counseling suites."
  },
  {
    id: "comp-22",
    image: "/logos/destylus.png",
    name: "Destylus Designer Pvt Ltd (Studio)",
    customer: "Destylus Designer Pvt Ltd",
    location: "Karapakkam, OMR Chennai",
    capacity: "17.7 TR/HP",
    scope: "Architecture Studio VRF System & Exposed Architectural Ducting",
    year: "2024",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "Modern open-ceiling duct design with individual zoning for design studios, conference rooms, and sample labs."
  },
  {
    id: "comp-18",
    image: "/logos/tmb-bank.svg",
    name: "TMB Bank (Old Washermenpet Branch)",
    customer: "TMB Bank",
    location: "Old Washermenpet, Chennai",
    capacity: "16 TR/HP",
    scope: "Banking Hall Ductable AC & Fresh Air Ventilation Setup",
    year: "2023",
    industry: "commercial-offices",
    brand: "Carrier",
    status: "completed",
    description: "Uniform cooling and positive pressure air delivery throughout customer lobby and back-office spaces."
  },
  {
    id: "comp-23",
    image: "/logos/aswin-kumar.svg",
    name: "Aswin Kumar Commercial Complex",
    customer: "Aswin Kumar",
    location: "Navalur, OMR Chennai",
    capacity: "16 TR/HP",
    scope: "Commercial Complex Inverter AC Network & Treated Fresh Air",
    year: "2024",
    industry: "commercial-offices",
    brand: "Blue Star",
    status: "completed",
    description: "Multi-tenant commercial building air conditioning optimized for low running costs."
  },
  {
    id: "comp-6",
    image: "/logos/vgn.webp",
    name: "VGN Corporate Office",
    customer: "VGN",
    location: "Anna Nagar, Chennai",
    capacity: "13.5 TR/HP",
    scope: "Premium Corporate Office VRF Air Conditioning & Linear Slot Diffusers",
    year: "2023",
    industry: "commercial-offices",
    brand: "Mitsubishi Electric",
    status: "completed",
    description: "Modern architectural HVAC installation with seamless ceiling integration and zone-level temperature control."
  },
  {
    id: "comp-17",
    image: "/logos/secretary-office.svg",
    name: "Secretary Administrative Office",
    customer: "Secretary",
    location: "Chetpet, Chennai",
    capacity: "11.5 TR/HP",
    scope: "Executive Office VRF Inverter Air Conditioning & Fresh Air Loop",
    year: "2022",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "Whisper-quiet executive office climate control with customized thermostat automation."
  },
  {
    id: "comp-24",
    image: "/logos/elegant-architect.svg",
    name: "Elegant Architect Office",
    customer: "Elegant Architect",
    location: "Nungambakkam, Chennai",
    capacity: "11.4 TR/HP",
    scope: "Architectural Studio Centralized VRF & Fresh Air Ventilation",
    year: "2023",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "High-efficiency VRF system complementing contemporary interior aesthetics and glass facade heat loads."
  },
  {
    id: "comp-10",
    image: "/logos/constronics.png",
    name: "Constronics Infra",
    customer: "Constronics Infra",
    location: "Alwarpet, Chennai",
    capacity: "11 TR/HP",
    scope: "Corporate Infrastructure Office Inverter Multi-Split Network",
    year: "2023",
    industry: "commercial-offices",
    brand: "Carrier",
    status: "completed",
    description: "Energy-efficient centralized air conditioning for executive cabins, boardroom, and design workstations."
  },
  {
    id: "comp-14",
    image: "/logos/tmb-bank.svg",
    name: "TMB Bank (George Town Branch)",
    customer: "TMB Bank",
    location: "George Town, Chennai",
    capacity: "10.5 TR/HP",
    scope: "Commercial Banking Hall HVAC & Server Room Cooling",
    year: "2023",
    industry: "commercial-offices",
    brand: "Carrier",
    status: "completed",
    description: "High-reliability air conditioning for commercial banking counter operations and secure cash-handling areas."
  },
  {
    id: "comp-8",
    image: "/logos/sowmya-residence.svg",
    name: "Sowmya Residence",
    customer: "Sowmya Residence",
    location: "Neelankarai, Chennai",
    capacity: "10 TR/HP",
    scope: "Luxury Beachside Villa Multi-Zone VRF System with Smart BMS Controls",
    year: "2024",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "Anti-corrosion treated coastal VRF installation providing silent, independent climate control in every room."
  },
  {
    id: "comp-20",
    image: "/logos/tmb-bank.svg",
    name: "TMB Bank (Thiruvottiyur Branch)",
    customer: "TMB Bank",
    location: "Thiruvottiyur, Chennai",
    capacity: "8 TR/HP",
    scope: "Retail Banking Branch Cassette & Split AC Network",
    year: "2023",
    industry: "commercial-offices",
    brand: "Carrier",
    status: "completed",
    description: "Energy-saving inverter cooling for bank branch customer counters and safe-deposit vault area."
  },
  {
    id: "comp-15",
    image: "/logos/canfin-homes.jpg",
    name: "Canfin Homes",
    customer: "Canfin Gomes",
    location: "West Tambaram, Chennai",
    capacity: "7.5 TR/HP",
    scope: "Financial Services Branch AC Installation & Ventilation",
    year: "2022",
    industry: "commercial-offices",
    brand: "Voltas",
    status: "completed",
    description: "Reliable commercial cooling designed for non-stop branch operations and customer consultation desks."
  },
  {
    id: "comp-21",
    image: "/logos/ramesh-residence.svg",
    name: "Mr. Ramesh Luxury Residence",
    customer: "Mr. Ramesh",
    location: "Kottivakkam, Chennai",
    capacity: "6.7 TR/HP",
    scope: "Coastal Villa Inverter VRF Air Conditioning & Concealed Ducts",
    year: "2023",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "Custom residential climate installation with concealed ducting and corrosion-resistant outdoor units."
  },
  {
    id: "comp-11",
    image: "/logos/entex.jpg",
    name: "Entex Pvt Ltd",
    customer: "Entex Pvt Ltd",
    location: "PCB Reddy, Anna Nagar, Chennai",
    capacity: "6 TR/HP",
    scope: "Corporate Engineering Office Climate Control Installation",
    year: "2022",
    industry: "commercial-offices",
    brand: "Daikin",
    status: "completed",
    description: "Compact, efficient split HVAC installation tailored for administrative staff comfort."
  }
];

export const amcProjects = [
  {
    id: "amc-1",
    image: "/logos/iiitdm.webp",
    name: "IIITDM Kanchipuram",
    customer: "IIITDM",
    location: "Kanchipuram, Tamil Nadu",
    capacity: "750 TR/HP",
    scope: "Comprehensive Central Chiller Plant, AHUs & Campus HVAC AMC",
    industry: "educational-institutions",
    brand: "Trane / Carrier",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Comprehensive 24/7 central HVAC maintenance for national institute lecture complexes, computer labs, and research halls."
  },
  {
    id: "amc-2",
    image: "/logos/cmrl.svg",
    name: "ABS General HVAC Solutions (CMRL)",
    customer: "ABS General HVAC Solutions",
    location: "CMRL, Ekkattuthangal, Chennai",
    capacity: "700 TR/HP",
    scope: "High-Tonnage Central Plant & Metro Rail Network Facility AMC",
    industry: "factories",
    brand: "Blue Star / York",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Critical infrastructure climate maintenance for Chennai Metro Rail operational facilities and technical complexes."
  },
  {
    id: "amc-3",
    image: "/logos/indian-bank.png",
    name: "Indian Bank Head Office",
    customer: "Indian Bank Head Office",
    location: "Parrys, Chennai",
    capacity: "494 TR/HP",
    scope: "Apex Banking Headquarters Central Chiller & VRF Network AMC",
    industry: "commercial-offices",
    brand: "Carrier / Daikin",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Apex corporate headquarters central plant maintenance with dedicated preventive visits and 2-hour breakdown response SLA."
  },
  {
    id: "amc-4",
    image: "/logos/anna-gowri.png",
    name: "Anna Gowri Educational Trust",
    customer: "Anna Gowri Educational Trust",
    location: "Puttur, Andhra Pradesh",
    capacity: "340 TR/HP",
    scope: "University Campus-Wide HVAC & Chiller Loop Maintenance Contract",
    industry: "educational-institutions",
    brand: "Voltas / Blue Star",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Year-round preventive maintenance across campus auditoriums, academic blocks, and administrative centers."
  },
  {
    id: "amc-5",
    image: "/logos/rbs.svg",
    name: "RBS (Royal Bank of Scotland Facility)",
    customer: "RBS",
    location: "Ambattur Industrial Estate, Chennai",
    capacity: "230 TR/HP",
    scope: "Financial & Tech Operations Facility Central Air Conditioning AMC",
    industry: "it-parks",
    brand: "Johnson Controls",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Mission-critical operations facility HVAC maintenance ensuring 99.9% continuous thermal uptime."
  },
  {
    id: "amc-6",
    image: "/logos/st-thomas.png",
    name: "St. Thomas College",
    customer: "St. Thomas College",
    location: "Koyambedu, Chennai",
    capacity: "198 TR/HP",
    scope: "College Campus, Auditoriums & Computer Labs HVAC AMC",
    industry: "educational-institutions",
    brand: "Blue Star",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Scheduled preventive servicing, filter sanitization, and coil chemical cleaning across campus buildings."
  },
  {
    id: "amc-7",
    image: "/logos/canara-bank.svg",
    name: "Canara Bank (Circle Office)",
    customer: "Canara bank, Circle Office",
    location: "Teynampet, Chennai",
    capacity: "175.5 TR/HP",
    scope: "Regional Circle Headquarters Central Air Conditioning AMC",
    industry: "commercial-offices",
    brand: "Voltas / Carrier",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Full-scale corporate banking circle headquarters HVAC preventive servicing and rapid breakdown support."
  },
  {
    id: "amc-8",
    image: "/logos/indian-bank.png",
    name: "Indian Bank (MRC Nagar)",
    customer: "Indian Bank",
    location: "MRC Nagar, Chennai",
    capacity: "158 TR/HP",
    scope: "Corporate Branch & Executive Office HVAC Maintenance Contract",
    industry: "commercial-offices",
    brand: "Carrier / Daikin",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "High-spec corporate banking center HVAC maintenance with periodic chemical descaling and refrigerant optimization."
  },
  {
    id: "amc-9",
    image: "/logos/sri-vasudeva.svg",
    name: "Sri Vasudeva Thirumana Maligai",
    customer: "Sri Vasudeva Thirumana Maligai",
    location: "Selaiyur, Chennai",
    capacity: "144 TR/HP",
    scope: "Grand Convention & Wedding Hall High-Capacity HVAC AMC",
    industry: "hotels",
    brand: "Blue Star",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Heavy part-load maintenance and pre-event cooling checkups for high-capacity convention hall."
  },
  {
    id: "amc-10",
    image: "/logos/gmmco-ckbirla.svg",
    name: "Gmmco Ltd (CK Birla Group)",
    customer: "Gmmco Ltd",
    location: "Guindy Industrial Estate, Chennai",
    capacity: "111 TR/HP",
    scope: "Heavy Engineering Corporate Facility & Training Center HVAC AMC",
    industry: "factories",
    brand: "Carrier",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Preventive HVAC maintenance for industrial equipment corporate headquarters and training auditoriums."
  },
  {
    id: "amc-11",
    image: "/logos/raja-gopal.svg",
    name: "Raja Gopal Thirumana Maligai",
    customer: "Raja Gopal Thirumana Maligai",
    location: "Tambaram, Chennai",
    capacity: "104.5 TR/HP",
    scope: "Marriage Palace & Banquet Hall HVAC Maintenance",
    industry: "hotels",
    brand: "Voltas",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Ductable cooling system servicing, electrical load balancing, and rapid seasonal support."
  },
  {
    id: "amc-12",
    image: "/logos/nadi.jpg",
    name: "Nadi Airtechnics",
    customer: "Nadi",
    location: "Madhavaram, Chennai",
    capacity: "103.5 TR/HP",
    scope: "Industrial Fan & Air Systems Manufacturing Facility AMC",
    industry: "factories",
    brand: "Blue Star",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Industrial climate maintenance covering production floors, testing chambers, and administrative blocks."
  },
  {
    id: "amc-13",
    image: "/logos/ananda-maligai.svg",
    name: "Ananda Thirumana Maligai",
    customer: "Ananda Thirumana Maligai",
    location: "Chromepet, Chennai",
    capacity: "99 TR/HP",
    scope: "Convention & Dining Complex Centralized AC Maintenance",
    industry: "hotels",
    brand: "Blue Star",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Reliable maintenance support ensuring peak cooling performance during large social and corporate gatherings."
  },
  {
    id: "amc-14",
    image: "/logos/rebar-design.png",
    name: "Rebar Design & Details Pvt Ltd",
    customer: "Rebar Design & Details Pvt Ltd",
    location: "Ekkattuthangal, Chennai",
    capacity: "85.5 TR/HP",
    scope: "Structural Engineering CAD Design Office VRF AMC",
    industry: "commercial-offices",
    brand: "Daikin",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Continuous climate care for high-density engineering CAD workstations and server rooms."
  },
  {
    id: "amc-15",
    image: "/logos/everest-bakery.svg",
    name: "Everest Bakery (6 Sites Network)",
    customer: "Everest Bakery",
    location: "6 Sites across Chennai",
    capacity: "76.5 TR/HP",
    scope: "Multi-Unit Food Production & Retail Store AC Network AMC",
    industry: "factories",
    brand: "Blue Star",
    contractType: "Comprehensive AMC",
    status: "active-amc",
    description: "Multi-site scheduled maintenance covering bakery manufacturing, packing zones, and retail outlets."
  },
  {
    id: "amc-16",
    image: "/logos/adpt-trust.svg",
    name: "ALANDUR DHARMA PARIPALANA TRUST",
    customer: "ALANDUR DHARMA PARIPALANA TRUST",
    location: "St. Thomas Mount, Chennai",
    capacity: "72 TR/HP",
    scope: "Community Trust Complex & Multi-Purpose Hall HVAC AMC",
    industry: "educational-institutions",
    brand: "Voltas",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Full preventive inspection protocol including compressor health, filter cleaning, and duct hygiene."
  },
  {
    id: "amc-17",
    image: "/logos/measi.png",
    name: "Measi Institute of Architecture",
    customer: "Measi Institute",
    location: "Royapettah, Chennai",
    capacity: "17 TR/HP",
    scope: "Architecture Design Studios & Seminar Hall AC Maintenance",
    industry: "educational-institutions",
    brand: "Daikin",
    contractType: "Annual Maintenance",
    status: "active-amc",
    description: "Scheduled academic session maintenance for design studios and audio-visual seminar rooms."
  }
];

export const projects = [...ongoingProjects, ...completedProjects, ...amcProjects];

export const caseStudies = [
  {
    id: "it-park-energy",
    title: "Saving 28% Energy Costs at OMR IT Tech Park",
    industry: "IT Parks",
    challenge: "A 400,000 sq.ft. IT Park in Chennai was experiencing astronomical electricity bills due to an outdated constant-speed chiller plant operating inefficiently under partial loads.",
    solution: "We retrofitted the facility with 2 x 400 TR Variable Speed Water-Cooled Screw Chillers, installed Variable Frequency Drives (VFDs) on the secondary pumps and AHUs, and integrated a Centralized Building Management System (BMS).",
    execution: "The retrofit was conducted in phases during weekends to ensure zero downtime or disruptions to the 24/7 IT operations. Pipe re-routing and chiller rigging were carefully coordinated.",
    result: "Average monthly power consumption dropped by 28%, resulting in annual savings of ₹64 Lakhs. The payback period was achieved in just 18 months.",
    savings: "28% Power Savings",
    outcome: "₹64 Lakhs Annual Savings",
    feedback: "Everest Air Conditioning delivered exactly what they promised. The energy auditing was spot-on, and the transition to the new chillers was seamless."
  },
  {
    id: "pharma-usfda-compliance",
    title: "USFDA Cleanroom Compliance for Bio-Pharma Unit",
    industry: "Pharmaceutical",
    challenge: "The client needed to upgrade their sterile formulation facility to meet USFDA Class 100 (ISO 5) and Class 10,000 (ISO 7) standards, requiring absolute control over particulate matter and relative humidity.",
    solution: "We installed custom double-skin cleanroom AHUs with H14 HEPA filtration (99.995% efficiency), desiccant dehumidifiers, and implemented differential pressure monitoring across zones.",
    execution: "Employed orbital welding for stainless steel piping and executed precise testing, adjusting, and balancing (TAB) to maintain positive pressure gradients.",
    result: "The facility successfully cleared the USFDA audit on the first attempt with zero HVAC-related observations.",
    savings: "0% Audit Deficiencies",
    outcome: "Successful USFDA Approval",
    feedback: "The engineering expertise shown by Everest was exceptional. Their documentation (IQ/OQ/PQ) made the validation process smooth."
  }
];

export const brands = [
  { name: "Daikin", category: "VRF & Chillers", country: "Japan" },
  { name: "Carrier", category: "Chillers & AHUs", country: "USA" },
  { name: "Blue Star", category: "Chillers & Packaged ACs", country: "India" },
  { name: "Voltas", category: "Commercial AC & Chillers", country: "India" },
  { name: "Mitsubishi Electric", category: "VRF & Split Systems", country: "Japan" },
  { name: "LG", category: "VRF Systems", country: "South Korea" },
  { name: "Hitachi", category: "VRF & Scroll Chillers", country: "Japan" },
  { name: "Trane", category: "Centrifugal & Screw Chillers", country: "USA" },
  { name: "York", category: "Chiller Plants", country: "USA" },
  { name: "Samsung", category: "DVM Pro VRF Systems", country: "South Korea" },
  { name: "Panasonic", category: "VRF & Ventilation", country: "Japan" },
  { name: "Schneider", category: "BMS & Controls", country: "France" },
  { name: "Honeywell", category: "BMS Sensors & Dampers", country: "USA" },
  { name: "Johnson Controls", category: "York Chillers & Automation", country: "USA" }
];

export const amcPlans = [
  {
    name: "Silver Maintenance Plan",
    level: "Basic Preventive Care",
    features: [
      "4 Scheduled Preventive Maintenance visits per year",
      "Comprehensive filter cleaning and coil washing",
      "Electrical contact and current analysis checkups",
      "Unlimited breakdown callouts (charged per visit)",
      "Response time within 24 hours"
    ],
    recommendedFor: "Small offices, showrooms, and retail stores."
  },
  {
    name: "Gold Comprehensive Plan",
    level: "All-Inclusive Care",
    features: [
      "4 Scheduled Preventive maintenance visits",
      "All breakdown callouts included at no additional cost",
      "Spare parts replacement (coils, compressors, fan motors, electronic cards)",
      "Refrigerant top-ups included",
      "Response time within 6 hours"
    ],
    recommendedFor: "Medium offices, hotels, and institutional campuses."
  },
  {
    name: "Premium 24x7 Critical Care",
    level: "Zero-Downtime SLA",
    features: [
      "Monthly preventive checks and diagnostics",
      "Dedicated resident technicians options",
      "24/7 Priority Emergency Support line",
      "Response time guaranteed under 2 hours",
      "No-cost replacement of high tonnage parts",
      "Annual energy audits and coil descaling cycles"
    ],
    recommendedFor: "Hospitals, IT parks, pharma units, and cold storage chains."
  }
];

export const blogs = [
  {
    id: "vrf-vs-chillers",
    title: "Difference Between VRF Systems & Chiller Plants: A Commercial Guide",
    category: "Engineering",
    author: "K. R. Raghavan (HVAC Design Lead)",
    readTime: "6 Min Read",
    excerpt: "Struggling to choose between VRF and a Chiller plant? Learn how building size, cooling loads, and zoning play a major role in the selection process.",
    content: "When designing high-capacity HVAC systems for commercial buildings, developers are face-to-face with a fundamental decision: Variable Refrigerant Flow (VRF) or Chiller Plants. While both deliver exceptional cooling, their operational mechanics, space footprints, and thermal efficiencies are highly distinct. VRF works by circulating refrigerant directly to individual fan coils in each room, allowing local zoning. Chillers, on the other hand, circulate chilled water through a network of pipes to Air Handling Units (AHUs). For spaces below 300 TR with highly partitioned zones (like hotels or premium offices), VRF is often the winner. For massive single-block complexes, IT parks, and factories exceeding 500 TR, water-cooled chillers remain the gold standard due to unmatched COP (Coefficient of Performance)."
  },
  {
    id: "hospital-hvac-guide",
    title: "Hospital HVAC Design: Ensuring Infection Control and Compliance",
    category: "Commercial HVAC",
    author: "Dr. S. Karthik (Cleanroom Consultant)",
    readTime: "8 Min Read",
    excerpt: "Discover the critical ventilation guidelines (NABH & ASHRAE 170) required to maintain sterile environments and prevent cross-contamination.",
    content: "Hospitals require more than temperature control; they require airborne pathogen control. In healthcare environments, HVAC systems are a primary line of defense against hospital-acquired infections (HAIs). Clean zones, such as Operating Theaters (OTs), require a positive pressure gradient relative to adjacent corridors to prevent non-sterile air infiltration. In contrast, COVID/TB isolation wards must maintain a negative pressure. Standard design calls for H14 HEPA filters that screen 99.995% of micro-particles, along with a minimum of 20 air changes per hour (ACH). Managing these loads while maintaining strict temperature and relative humidity requires double-skin AHUs with thermal break profiles and variable air volume systems."
  },
  {
    id: "hvac-amc-checklist",
    title: "The Ultimate Commercial HVAC AMC Checklist for Facility Managers",
    category: "Maintenance",
    author: "R. Loganathan (AMC Service Head)",
    readTime: "5 Min Read",
    excerpt: "Avoid unexpected central plant failures. Here is the checklist your maintenance team must check during routine AMC visits.",
    content: "Preventive maintenance is the single most cost-effective decision a facility manager can make. Studies show that regular coil descaling and refrigerant tracking can reduce compressor power draw by up to 15%. A standard commercial HVAC inspection checklist should include: testing compressor winding resistance, verifying electrical contractor contacts, checking refrigerant operating pressures, analyzing fan belt tension, cleaning condensate drain trays to prevent water leaks, and testing emergency fire damper interlocks."
  }
];

export const localSEOData = {
  chennai: {
    city: "Chennai",
    intro: "Everest Air Conditioning is Chennai's premier B2B Commercial HVAC contractor. Headquartered in Chennai, we have been serving the metropolitan city's IT corridors (OMR & GST Road), industrial zones (Sriperumbudur, Oragadam), and healthcare networks for over 30 years.",
    services: ["Central Chiller Plant Installation", "VRF / VRV Projects", "Hygienic Cleanroom HVAC", "High-tonnage Ventilation", "Industrial Process Cooling", "24/7 HVAC AMC Support"],
    coverage: ["Guindy", "OMR", "GST Road", "Ambattur Industrial Estate", "Sriperumbudur", "Oragadam", "T Nagar", "Velachery", "Adyar", "Perungudi"]
  },
  coimbatore: {
    city: "Coimbatore",
    intro: "Known as the Manchester of South India, Coimbatore's textile mills, manufacturing units, and rapid commercialization demand high-tonnage industrial cooling. Everest HVAC designs and maintains custom cooling plants across the region.",
    services: ["Industrial Air Washers", "Process Chillers", "Warehouse Ventilation", "Corporate VRF Systems", "Commercial AMC Services"],
    coverage: ["Peelamedu", "Gandhipuram", "Saravanampatti", "Singanallur", "Pollachi Road", "Kurichi Industrial Area"]
  },
  bangalore: {
    city: "Bangalore",
    intro: "With high-density tech parks and global data hubs in Whitefield and Electronic City, Bangalore requires highly energy-efficient and precise sensible heat extraction. We deliver green building compliant VRF and Chiller solutions.",
    services: ["Data Center Precision AC", "Centrifugal Chiller Systems", "VRF Heat Recovery Systems", "Green Building HVAC Audits"],
    coverage: ["Whitefield", "Electronic City", "Manyata Tech Park", "Koramangala", "Indiranagar", "Marathahalli"]
  },
  madurai: {
    city: "Madurai",
    intro: "For the southern business hub of Madurai, Everest HVAC delivers robust commercial air conditioning systems for hospitals, shopping malls, and educational institutions designed to operate in extreme summer heat.",
    services: ["Commercial DX Packaged Units", "Hospital HVAC & HEPA Integration", "Educational HVAC Systems", "AMC Support Services"],
    coverage: ["Anna Nagar", "KK Nagar", "Kappalur Industrial Estate", "Sellur", "Simmakkal"]
  },
  trichy: {
    city: "Trichy",
    intro: "We provide high-capacity ventilation, ducting, and commercial air conditioning solutions for Trichy's fabrication industries, healthcare centers, and educational campuses.",
    services: ["Heavy-duty Ducting Systems", "Basement Smoke Ventilation", "Packaged Air Conditioners", "AMC Contracts"],
    coverage: ["Thuvakudi Industrial Area", "Cantonment", "Srirangam", "Kattur"]
  },
  salem: {
    city: "Salem",
    intro: "Salem's steel plants, metallurgical units, and commercial establishments rely on Everest HVAC for specialized heat extraction, ventilation, and chiller setups.",
    services: ["Industrial Plant Ventilation", "Process Cooling Chillers", "Commercial AC AMC", "Duct Fabrication"],
    coverage: ["Steel Plant Road", "Meyyanur", "Shevapet", "Ammapet"]
  },
  hosur: {
    city: "Hosur",
    intro: "As a manufacturing powerhouse bordering Bangalore, Hosur's electronics, automotive, and pharmaceutical plants rely on our high-standards cleanroom HVAC and process chillers.",
    services: ["FDA Cleanroom HVAC", "Automotive Assembly Exhausts", "Precision Chilled Water Systems", "AMC SLA Support"],
    coverage: ["SIPCOT Phase I & II", "Bagalur Road", "Mathigiri", "Zuzuvadi"]
  },
  pondicherry: {
    city: "Pondicherry",
    intro: "We design and install specialized marine-grade coating condenser HVAC units and GMP pharma cleanrooms for Pondicherry's coastal commercial complexes and active chemical formulation units.",
    services: ["USFDA Pharma Cleanroom Setup", "Anti-corrosive HVAC Coil Coatings", "Hotel VRF Systems", "AMC & Preventive Audits"],
    coverage: ["Mettupalayam Industrial Estate", "White Town", "Gorimedu", "Kalapet"]
  }
};

export const seoLandingPages = {
  "commercial-hvac": {
    title: "Commercial HVAC Systems Design & Installation",
    heroHeading: "High-Performance Commercial HVAC Engineering",
    problem: "Outdated or poorly designed HVAC systems lead to hot/cold spots, high maintenance frequency, poor indoor air quality, and astronomical energy bills.",
    challenges: "Commercial buildings feature diverse zones (meeting rooms, server rooms, lobbies) which require continuous, variable load management without creating noise or thermal imbalance.",
    solution: "We provide complete design-to-delivery services incorporating accurate heat load calculations (ASHRAE), layout drafting in 3D BIM, duct network design, equipment selection, and turnkey commissioning.",
    process: ["Load Auditing", "3D CAD Layout", "Procurement & Rigging", "Duct & Piping Layout", "Balancing & Commissioning"]
  },
  "industrial-cooling": {
    title: "Industrial Process Cooling & Plant Ventilation",
    heroHeading: "Heavy-Duty Industrial Cooling Solutions",
    problem: "High temperatures in factory floors degrade machinery life, reduce worker productivity, and fail safety regulations.",
    challenges: "Factories feature heavy dust, soot, oil fumes, and machinery heat that can quickly clog regular air filters and damage standard cooling systems.",
    solution: "We deploy heavy-duty process chillers, evaporative air washers, air scrubbing systems, and forced drafts to keep manufacturing floors well-ventilated and comfortable.",
    process: ["Process Load Assessment", "Exhaust Routing", "Air Washer Assembly", "Testing Static Pressures"]
  },
  "cold-storage": {
    title: "B2B Cold Storage & Logistical Refrigeration",
    heroHeading: "Sub-Zero Thermal Storage & Warehousing Systems",
    problem: "Even a 1°C temperature drift in pharmaceutical or frozen food storage can ruin millions of rupees worth of inventory.",
    challenges: "Cold storage must maintain precise sub-zero climates continuously, resisting ambient heat transfer and frost build-up from loading bays.",
    solution: "Custom-built cold rooms utilizing PUF panels of 100-150mm thickness, energy-efficient evaporator units, hermetic compressors, and cloud-linked IoT temperature sensors with auto-alarms.",
    process: ["Insulation Layering", "Refrigeration Unit Rigging", "Sensor Calibration", "Pull Down Test"]
  },
  "hvac-amc": {
    title: "Commercial HVAC Annual Maintenance Contracts (AMC)",
    heroHeading: "Guaranteed HVAC Reliability with Professional AMC",
    problem: "Unscheduled HVAC breakdowns lead to lost business hours, tenant complaints, and expensive emergency replacements.",
    challenges: "Central chiller plants and VRF loops have complex mechanical elements that degrade over time, leading to hidden efficiency losses of up to 30%.",
    solution: "Our SLAs (Gold & Premium) feature round-the-clock technician availability, periodic coil descaling, preventive checklists, and inclusive parts replacements to ensure 100% uptime.",
    process: ["Site Onboarding Audit", "Scheduling Preventive Visits", "Health Reports & Optimization", "24/7 Hotline Support"]
  }
};

export const productCatalog = {
  installations: [
    "Cold Room Installation Service",
    "Air Conditioner Installation Service",
    "Air Duct Installation Service",
    "Water Cooler Installation Service"
  ],
  maintenance: [
    "Water Cooler Maintenance Service",
    "Air Duct Maintenance Service",
    "Air Conditioner Maintenance Service",
    "Cold Room Maintenance Service"
  ],
  repairing: [
    "Water Cooler Repair Service",
    "Air Conditioner Repair Service",
    "Cold Room Repair Service"
  ],
  airConditioners: [
    "Tower Air Conditioner",
    "Central Air Conditioner",
    "Split Air Conditioner",
    "Cassette Air Conditioner",
    "Ducted Air Conditioner",
    "Window Air Conditioner",
    "Ogeneral Split Ac",
    "Mitsubishi Air Conditioning",
    "Mitsubishi Outdoor Unit",
    "Ogeneral Airconditioner",
    "Airconditioner",
    "Mitsubishi Ac"
  ],
  coldCoolers: [
    "Freezer and Bottle Cooler",
    "SS Water Cooler with 3 Taps",
    "Vaccine Storage Cooler",
    "Visi Cooler 220"
  ],
  iceMachines: [
    "Ice Cream Display Machine",
    "Ice Cube Machine"
  ],
  coldRooms: [
    "Freezer Cold Room",
    "Commercial Cold Room",
    "Modular Cold Room",
    "Cold Storage Room"
  ],
  purifiers: [
    "RO Water Purifiers Cooler"
  ]
};

